CREATE TYPE IF NOT EXISTS perfil_enum AS VARCHAR(50);
CREATE TYPE IF NOT EXISTS genero_enum AS VARCHAR(50);
CREATE TYPE IF NOT EXISTS nivel_experiencia AS VARCHAR(50);

CREATE TABLE IF NOT EXISTS tb_aluno (
    id_aluno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    idade INT,
    peso NUMERIC(5,2),
    altura NUMERIC(3,2),
    genero VARCHAR(50),
    nivel_experiencia VARCHAR(50),
    dias_disponiveis_semana INT,
    restricao_medica TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tb_funcionario (
    id_funcionario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    registro_academico VARCHAR(50),
    perfil VARCHAR(50),
    ativo BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tb_tipo_treino (
    id_tipo_treino BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS tb_plano_treino (
    id_plano BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_treino BIGINT NOT NULL REFERENCES tb_tipo_treino(id_tipo_treino),
    id_professor_criador BIGINT NOT NULL REFERENCES tb_funcionario(id_funcionario),
    titulo VARCHAR(100) NOT NULL,
    descricao VARCHAR(250) NOT NULL,
    nivel_recomendado VARCHAR(50),
    ativo BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
